// Per-ecosystem Codespace definitions, and the generator that turns them into
// .devcontainer/<ecosystem>/devcontainer.json.
//
// The files are generated rather than hand-maintained because the one thing
// they each need to know — which *other* demos to hide from the Explorer —
// changes every time a demo is added. Sixteen hand-written copies of that list
// is sixteen chances to forget one, and the failure is silent: the Explorer
// just shows clutter. Here it is derived from demos.json.
//
// `scripts/sync-devcontainers.mjs` writes them; `scripts/verify-devcontainers.mjs`
// checks the committed files match, so a stale one fails CI.

/**
 * What each ecosystem's container needs, beyond the shared shape.
 *
 *   image     devcontainer base image
 *   features  extra devcontainer features (Node is added automatically wherever
 *             the base image does not already provide it, because every demo
 *             runs the shared prepare script)
 *   setup     creation command, if it differs from the plain prepare step
 *   settings  extra VS Code settings for this demo
 */
export const ECOSYSTEM_CONTAINERS = {
  npm: {
    image: 'mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm',
    node: false,
    // Install after preparing, so the editor's own TypeScript server reports
    // the same error the upgrade really causes.
    setup: 'node scripts/prepare-demo.mjs npm && npm --prefix demos/npm install --no-audit --no-fund',
  },
  pypi: {
    image: 'mcr.microsoft.com/devcontainers/python:1-3.12-bookworm',
  },
  go: {
    image: 'mcr.microsoft.com/devcontainers/go:1-1.22-bookworm',
    // golang.org/x/exp ships only pseudo-versions, which Drift reads as a patch
    // move. .github/drift.yml opts the repo in; this makes the extension agree
    // without depending on config-file precedence.
    settings: { 'drift.analysis.includePatch': true },
  },
  cargo: {
    image: 'mcr.microsoft.com/devcontainers/rust:1-1-bookworm',
    // Drift's Rust surface diff needs `cargo public-api` and the nightly
    // toolchain. Provisioned up front; see .devcontainer/cargo/setup.sh.
    setup: '.devcontainer/cargo/setup.sh',
  },
  maven: {
    image: 'mcr.microsoft.com/devcontainers/java:1-21-bookworm',
    features: {
      'ghcr.io/devcontainers/features/java:1': { version: 'none', installMaven: true },
    },
  },
  rubygems: {
    image: 'mcr.microsoft.com/devcontainers/ruby:1-3.3-bookworm',
  },
};

/** Node feature, added wherever the base image does not already ship it. */
const NODE_FEATURE = { 'ghcr.io/devcontainers/features/node:1': { version: 'lts' } };

/**
 * Build the devcontainer object for one demo.
 *
 * @param {object} demo      the demos.json entry
 * @param {object[]} allDemos every demos.json entry, for the exclude list
 * @param {object} expected  the demo's expected.json, for the files to open
 */
export function buildDevcontainer(demo, allDemos, expected) {
  const spec = ECOSYSTEM_CONTAINERS[demo.ecosystem];
  if (!spec) return null;

  const features = { ...(spec.node === false ? {} : NODE_FEATURE), ...(spec.features ?? {}) };

  // Hide every *other* demo, derived rather than restated.
  const filesExclude = {};
  for (const other of allDemos) {
    if (other.ecosystem !== demo.ecosystem) filesExclude[other.demoPath] = true;
  }

  return {
    name: `Drift demo — ${demo.label}`,
    image: spec.image,
    ...(Object.keys(features).length > 0 ? { features } : {}),
    onCreateCommand: spec.setup ?? `node scripts/prepare-demo.mjs ${demo.ecosystem}`,
    waitFor: 'onCreateCommand',
    customizations: {
      vscode: {
        extensions: ['drift.drift'],
        settings: {
          'drift.session.mode': 'ask',
          'drift.analysis.runOnStartup': true,
          ...(spec.settings ?? {}),
          'files.exclude': filesExclude,
        },
      },
      codespaces: {
        openFiles: [
          `${demo.demoPath}/DEMO.md`,
          `${demo.demoPath}/${expected.expectedAffectedFiles[0]}`,
          `${demo.demoPath}/${expected.dependencyFiles[0]}`,
        ],
      },
    },
  };
}

/** The header comment written above every generated devcontainer. */
export const GENERATED_HEADER = `// Generated by scripts/sync-devcontainers.mjs from .drift-demo/demos.json.
// Do not edit by hand — edit scripts/lib/devcontainer-spec.mjs and re-run:
//
//     node scripts/sync-devcontainers.mjs
//
// The Explorer exclude list below is derived from demos.json, so adding a demo
// updates every environment at once instead of leaving fifteen stale copies.
`;
